Updating Log, warn, info, error
Updating Log to tee to file. Updating warn, info, error to use Log.

diff --git a/plexupdate-core b/plexupdate-core
--- a/plexupdate-core
+++ b/plexupdate-core
@@ -132,6 +132,23 @@ getPlexWebToken() {
 }
 
 # HELPERS
+# Log - Echo messages with date and timestamp
+Log () {
+	logText=$1
+	# indent lines except for program entry and exit
+	if [[ "${logText}" == "-->"* ]];then
+		logText="${logText}`basename $0`: launched..."
+	else
+		if [[ "${logText}" == "<--"* ]];then
+			logText="${logText}`basename $0`: ...terminated"
+		else
+		logText="   ${logText}"
+		fi
+	fi
+	date=$(/bin/date)
+	echo "${date/E[DS]T /} ${logText}" | /usr/bin/tee -a "${logFile}"
+}
+
 keypair() {
 	local key="$( rawurlencode "$1" )"
 	local val="$( rawurlencode "$2" )"
@@ -212,32 +229,15 @@ verifyToken() {
 
 # SHARED
 warn() {
-	echo "WARNING: $@" >&1
+	Log "WARNING: $@" >&1
 }
 
 info() {
-	echo "$@" >&1
+	Log "$@" >&1
 }
 
 error() {
-	echo "ERROR: $@" >&2
-}
-
-# Log - Echo messages with date and timestamp
-Log () {
-	logText=$1
-	# indent lines except for program entry and exit
-	if [[ "${logText}" == "-->"* ]];then
-		logText="${logText}`basename $0`: launched..."
-	else
-		if [[ "${logText}" == "<--"* ]];then
-			logText="${logText}`basename $0`: ...terminated"
-		else
-		logText="   ${logText}"
-		fi
-	fi
-	date=$(/bin/date)
-	echo "${date/E[DS]T /} ${logText}" >> "${logFile}"
+	Log "ERROR: $@" >&2
 }
 
 # Intentionally leaving this hard to find so that people aren't trying to use it manually.
